# Export environment variables to the system DBUS
exec_always dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec_always dbus-update-activation-environment --systemd QT_QPA_PLATFORMTHEME=qt5ct
exec_always dbus-update-activation-environment --systemd QT_QPA_PLATFORMTHEME=qt6ct
exec_always dbus-update-activation-environment --systemd QT_QPA_PLATFORM=wayland;xcb

