exec_always killall wl-clip-persist
exec_always wl-clip-persist --clipboard regular &

exec_always killall wl-paste
exec_always wl-paste --watch cliphist store &

bindsym $mod+h exec foot -T Cliphist sh -c 'cliphist list | fzf --no-sort | cliphist decode | wl-copy'
for_window [title="^Cliphist$"] floating enable, resize set 900 500
#bindsym $mod+h exec nwg-clipman -w
# vim: ft=swayconfig
